
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - MONGODB_URL=mongodb://mongo:27017/compliance_db
      - APP_NAME=Compliance Scan Portal
      - DEBUG=True
      - API_PREFIX=/api/v1
      - LOG_LEVEL=INFO
      - TEMP_UPLOAD_DIR=/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6-jammy
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: --quiet

volumes:
  mongodb_data:
